buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Use a compatible version of the Android Gradle Plugin for SDK 35
        classpath 'com.android.tools.build:gradle:8.2.0'  // Update to a version that supports SDK 35
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0'  // Ensure Kotlin plugin is up-to-date
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
